services:
  postgres:
    image: postgres:16
    container_name: groupone_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: groupone_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/fes-wiesbaden/backend:latest
    container_name: groupone_backend
    platform: linux/arm64
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: groupone_db
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ../backend
      args:
        VITE_API_URL: "http://localhost:8080"

  frontend:
    image: ghcr.io/fes-wiesbaden/frontend:latest
    container_name: groupone_frontend
    platform: linux/arm64
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL="http://localhost:8080"

volumes:
  postgres_data:
